version: "3.9"

services:
  copyparty:
    user: "1000"
    ports:
      - 3923:3923
    volumes:
      - ./cfg:/cfg:ro
      - ./data:/w
      - /media/parham-main/parham/books:/w/books:ro
    image: ghcr.io/9001/copyparty-ac
