version: "3.9"

services:
  copypartry:
    extends:
      file: docker-compose.yml
      service: copyparty
    volumes:
      - type: bind
        source: /media/parham-main/parham/books
        target: /w/books
        read_only: true
        bind:
          create_host_path: false
