version: "3.9"

services:
  copypartry:
    extends:
      file: docker-compose.yml
      service: copyparty
    volumes:
      - type: bind
        source: /media/parham-secret/parham/
        target: /w/secret
        read_only: true
        bind:
          create_host_path: false
